name: Ruff lint

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  ruff-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
      
      - name: Install ruff
        run: uv tool install ruff

      - name: Lint with ruff
        run: uvx ruff check .